% Theia to OpenSim batch processing pipeline
%
% This script:
%   1. Selects C3D files from a folder or manual file selection
%   2. Converts each Theia C3D to a virtual-marker C3D using theia2c3d
%   3. Optionally low-pass filters the virtual markers
%   4. Writes a TRC file from the virtual markers
%   5. Scales an OpenSim model, either per trial or from a calibration trial
%   6. Runs inverse kinematics
%   7. Runs body analysis
%
% IMPORTANT:
%   The TRC file output is required for OpenSim scaling and IK.
%
%% AUTHORS
% Glen Lichtwark
%   Queensland University of Technology
%
% Logan Wade
%   University of New South Wales
%
% Last Updated: June 2026

clear
clc
import org.opensim.modeling.*

%% ========================================================================
% USER SETTINGS
%
% IMPORTANT:
% Update these paths before running on a different computer.
%
% Files to edit:
%   generic_model
%   scale_setup
%   ik_setup
%
% Processing setting:
%   filter_freq
% ========================================================================

% Low-pass filter frequency for C3D to TRC processing
filter_freq = 10;

% Generic OpenSim model used for scaling
generic_model = 'C:\Users\z3550257\Dropbox\University\GitHubClones\TheiaOpensim\TheiaModel\Rajagopal2015_Theia3D_V5.osim';

% Scale Tool XML setup file
scale_setup = 'C:\Users\z3550257\Dropbox\University\GitHubClones\TheiaOpensim\TheiaModel\scale_setup_v5.xml';

% Inverse Kinematics XML setup file
ik_setup = 'C:\Users\z3550257\Dropbox\University\GitHubClones\TheiaOpensim\TheiaModel\ik_setup_v5.xml';

% Conversion options
crop = false;
show_animation = false;

% Always true for this OpenSim pipeline
TRCoutput = true;

%% ========================================================================
% USER INPUT - Select input source
% ========================================================================

answer = questdlg( ...
    'Process a folder or selected files?', ...
    'Select input', ...
    'Folder', 'Files', 'Cancel');

if isempty(answer) || strcmpi(answer, 'Cancel')
    disp('User cancelled.')
    return
end

files = {};
participantFolder = '';

switch answer

    case 'Folder'

        folder = uigetdir(pwd, 'Select participant folder containing C3D files');

        if isequal(folder, 0)
            disp('User cancelled.')
            return
        end

        % Use the chosen folder as the participant-level output folder
        participantFolder = folder;

        % Get all .c3d files in folder and subfolders
        filesMeta = dir(fullfile(folder, '**', '*.c3d'));

        % Exclude any files from folders named 'unused'
        isUnused = contains({filesMeta.folder}, [filesep 'unused' filesep], ...
            'IgnoreCase', true);

        % Exclude files that contain '_filt'
        isFilt = contains({filesMeta.name}, '_filt', ...
            'IgnoreCase', true);

        % Exclude files already generated by theia2c3d
        isTheiaOutput = endsWith({filesMeta.name}, '_Theia.c3d', ...
            'IgnoreCase', true);

        filesMeta = filesMeta(~(isUnused | isFilt | isTheiaOutput));
        files = fullfile({filesMeta.folder}, {filesMeta.name});

    case 'Files'

        [filesSel, pathSel] = uigetfile( ...
            '*.c3d', ...
            'Select source C3D files - do not select *_Theia.c3d files', ...
            'MultiSelect', 'on');

        if isequal(filesSel, 0)
            disp('User cancelled.')
            return
        end

        if ischar(filesSel)
            files = {fullfile(pathSel, filesSel)};
        else
            files = fullfile(pathSel, filesSel);
        end

        % Exclude manually selected files that are already Theia-converted outputs.
        % These files will be regenerated and may otherwise be overwritten.
        [~, fileNames, fileExts] = cellfun(@fileparts, files, 'UniformOutput', false);
        fullNames = strcat(fileNames, fileExts);

        isTheiaOutput = endsWith(fullNames, '_Theia.c3d', ...
            'IgnoreCase', true);

        if any(isTheiaOutput)
            warning('Excluding %d already-converted _Theia.c3d file(s).', sum(isTheiaOutput));
            files = files(~isTheiaOutput);
        end

        if isempty(files)
            disp('No valid source C3D files selected after excluding _Theia.c3d files.')
            return
        end

        % For manual file selection, ask where OpenSim outputs should go
        participantFolder = uigetdir(pathSel, 'Select participant output folder');

        if isequal(participantFolder, 0)
            disp('User cancelled.')
            return
        end
end

if isempty(files)
    disp('No C3D files selected.')
    return
end

[~, participant_code] = fileparts(participantFolder);


%% ========================================================================
% USER INPUT - Participant mass
% ========================================================================

massAnswer = inputdlg( ...
    'Participant mass (kg):', ...
    'Participant Mass', ...
    1, ...
    {'76'});

if isempty(massAnswer)
    disp('User cancelled.')
    return
end

mass = str2double(massAnswer{1});

if isnan(mass) || mass <= 0
    error('Participant mass must be a positive number.')
end

%% ========================================================================
% USER INPUT - Scaling mode
% ========================================================================

scaleMode = questdlg( ...
    'Scale a model for every file, or use one calibration trial?', ...
    'Scaling mode', ...
    'Every file', 'Calibration trial', 'Every file');

if isempty(scaleMode)
    disp('User cancelled.')
    return
end

useStaticModel = strcmpi(scaleMode, 'Calibration trial');
staticModelPath = '';
staticTrialIdx = [];

% Build a readable trial list
trialLabels = cell(size(files));

for k = 1:numel(files)
    [~, trialName, trialExt] = fileparts(files{k});
    trialLabels{k} = [trialName trialExt];
end

if useStaticModel

    [staticTrialIdx, ok] = listdlg( ...
        'PromptString', 'Select the calibration trial:', ...
        'SelectionMode', 'single', ...
        'ListString', trialLabels);

    if ~ok
        disp('User cancelled.')
        return
    end

    staticTrialPath = files{staticTrialIdx};

    % Build one scaled model from the selected calibration trial
    staticModelPath = build_static_scaled_model( ...
        staticTrialPath, ...
        mass, ...
        generic_model, ...
        scale_setup, ...
        filter_freq, ...
        crop, ...
        show_animation, ...
        participantFolder);

end

% Exclude calibration trial from IK and body analysis
filesToProcess = files;

if useStaticModel
    filesToProcess(staticTrialIdx) = [];
end

if isempty(filesToProcess)
    disp('Only the calibration trial was selected. No movement trials left to process.')
    return
end



%% RUN SCRIPT
%% Process each file
for i = 1:numel(filesToProcess)
    fpath = filesToProcess{i};
    [trialFolder, trialName, ext] = fileparts(fpath);

    % Output paths
    theia_fpath = fullfile(trialFolder, [trialName '_Theia.c3d']);

    disp(['Processing: ' fpath])

    %Create c3d file
    data = theia2c3d( ...
        fpath, ...
        theia_fpath, ...
        TRCoutput, ...
        filter_freq, ...
        crop, ...
        show_animation);

    if ~isfield(data, 'TRC_Filename') || ~isfile(data.TRC_Filename)
        error('TRC file was not created for trial: %s', fpath)
    end

    disp(['Created Theia C3D file - ' theia_fpath])
    disp(['Created TRC file - ' data.TRC_Filename])


    % Use this if you need GRF - this needs to be updated!!!
    %data = ezc3d_c3d2trc_QUT(theia_fpath, filter_freq);

    % Ensure output directories exist
    modelScalingDir = fullfile(participantFolder, 'ModelScaling');
    ikDir           = fullfile(participantFolder, 'InverseKinematics');
    bodyDir         = fullfile(participantFolder, 'BodyAnalysis');

    if ~exist(modelScalingDir, 'dir'), mkdir(modelScalingDir); end
    if ~exist(ikDir, 'dir'), mkdir(ikDir); end
    if ~exist(bodyDir, 'dir'), mkdir(bodyDir); end

    % Scale the model for this file, or reuse the static model
    if useStaticModel
        data.ScaledModel = staticModelPath;
    else
        data = build_scaled_model_from_trc(data, mass, ...
            generic_model, scale_setup, participantFolder, participant_code);
    end

    if ~isfield(data, 'ScaledModel') || ~isfile(data.ScaledModel)
        error('Scaled model was not created for trial: %s', fpath)
    end

    % Run inverse kinematics
    data = run_inverse_kinematics(data, ik_setup, participantFolder, trialName);

    % Run body analysis
    data = run_body_analysis(data, participantFolder, trialName);

    disp('Done.')
    disp('----------------------------------------')
end

%% ========================================================================
% Local functions
% ========================================================================

function staticModelPath = build_static_scaled_model(staticTrialPath, mass, generic_model, scale_setup, filter_freq, crop, show_animation, participantFolder)

[staticFolder, staticName, ~] = fileparts(staticTrialPath);

staticTheia = fullfile(staticFolder, [staticName '_Theia.c3d']);

disp('Running static calibration conversion...')

staticData = theia2c3d( ...
    staticTrialPath, ...
    staticTheia, ...
    true, ...
    filter_freq, ...
    crop, ...
    show_animation);

if ~isfield(staticData, 'TRC_Filename') || ~isfile(staticData.TRC_Filename)
    error('Calibration TRC file was not created: %s', staticTrialPath)
end

staticData = build_scaled_model_from_trc( ...
    staticData, ...
    mass, ...
    generic_model, ...
    scale_setup, ...
    participantFolder, ...
    'static');

[scaleDir, ~, ~] = fileparts(staticData.ScaledModel);
staticModelPath = staticData.ScaledModel;

disp(['Static model created - ' staticModelPath])
end

function data = build_scaled_model_from_trc(data, mass, generic_model, scale_setup, trialFolder, participant_code)
import org.opensim.modeling.*

disp('Running Scale Tool...')

[~, name, ~] = fileparts(data.TRC_Filename);
[~, mod_name, ~] = fileparts(generic_model);

outDir = fullfile(trialFolder, 'ModelScaling');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

ScTool = ScaleTool(scale_setup);
ScTool.setName(participant_code);
ScTool.setPathToSubject('');

GMM = ScTool.getGenericModelMaker;
MS  = ScTool.getModelScaler;
MP  = ScTool.getMarkerPlacer;

GMM.setModelFileName(generic_model);
GMM.setName(mod_name);

scaleSetFile    = fullfile(outDir, [name '_scaleSetApplied.xml']);
scaledModelFile = fullfile(outDir, [name '_Scaled.osim']);
markersFile     = fullfile(outDir, [name '_markersScaled.xml']);

% Delete existing output files before running Scale Tool
filesToDelete = { ...
    scaleSetFile, ...
    scaledModelFile, ...
    markersFile};

for f = 1:numel(filesToDelete)
    if isfile(filesToDelete{f})
        delete(filesToDelete{f});
    end
end

% Check that the output directory is writable
testFile = fullfile(outDir, 'write_test.tmp');
[fid, msg] = fopen(testFile, 'w');

if fid == -1
    error('Cannot write to ModelScaling folder: %s\n%s', outDir, msg);
else
    fclose(fid);
    delete(testFile);
end

MS.setOutputScaleFileName(scaleSetFile);
MS.setOutputModelFileName(scaledModelFile);
MP.setOutputModelFileName(scaledModelFile);
MP.setOutputMarkerFileName(markersFile);

MS.setMarkerFileName(data.TRC_Filename);
MP.setMarkerFileName(data.TRC_Filename);

%Time variables
markerData = MarkerData(data.TRC_Filename);
InitialTime = markerData.getStartFrameTime();
FinalTime   = InitialTime + 0.5;
lastTime = markerData.getLastFrameTime();
if FinalTime > lastTime
    FinalTime = lastTime;
end

time_range = ArrayDouble;
time_range.append(InitialTime);
time_range.append(FinalTime);

MS.setTimeRange(time_range);
MP.setTimeRange(time_range);

ScTool.setSubjectMass(mass);

setupFile = fullfile(outDir, [participant_code '_setupScale.xml']);
ScTool.print(setupFile);

ScTool.run();

data.ScaledModel = scaledModelFile;
end

function data = run_inverse_kinematics(data, ik_setup, trialFolder, trialName)
import org.opensim.modeling.*

disp('Running Inverse Kinematics Tool...')

ikDir = fullfile(trialFolder, 'InverseKinematics');
if ~exist(ikDir, 'dir')
    mkdir(ikDir);
end

ikTool = InverseKinematicsTool(ik_setup);
model = Model(data.ScaledModel);
ikTool.setModel(model);

marker_file = data.TRC_Filename;
[~, fname, ~] = fileparts(marker_file);

mot_file  = fullfile(ikDir, [fname '.mot']);
setup_file = fullfile(ikDir, [fname '_iksetup.xml']);
data.MOT_Filename = mot_file;

markerData = MarkerData(marker_file);
initial_time = markerData.getStartFrameTime();
final_time   = markerData.getLastFrameTime();

ikTool.setMarkerDataFileName(marker_file);
ikTool.setStartTime(initial_time);
ikTool.setEndTime(final_time);
ikTool.setOutputMotionFileName(mot_file);
ikTool.setName(fname);
ikTool.setResultsDir([ikDir filesep]);

ikTool.print(setup_file);
ikTool.run();

data.ik_results = load_sto_file(mot_file);

disp('IK complete.')
end

function data = run_body_analysis(data, trialFolder, trialName)
import org.opensim.modeling.*

disp('Running Body Analysis Tool...')

bodyDir = fullfile(trialFolder, 'BodyAnalysis');
if ~exist(bodyDir, 'dir')
    mkdir(bodyDir);
end

% Use the IK filename as the base name so body analysis matches IK output names
[~, fname, ~] = fileparts(data.MOT_Filename);

motData = Storage(data.MOT_Filename);
initial_time = motData.getFirstTime();
final_time   = motData.getLastTime();

M = Model(data.ScaledModel);

Body_AnL = BodyKinematics(M);
Body_AnL.setStartTime(initial_time);
Body_AnL.setEndTime(final_time);
M.addAnalysis(Body_AnL);

tool = AnalyzeTool();
tool.setModel(M);
tool.setModelFilename(data.ScaledModel);
tool.setCoordinatesFileName(data.MOT_Filename);
tool.setLoadModelAndInput(true);
tool.setSolveForEquilibrium(true);
tool.setName(fname);
tool.setResultsDir([bodyDir filesep]);
tool.setStartTime(initial_time);
tool.setFinalTime(final_time);

AS = tool.getAnalysisSet;
AS.set(0, Body_AnL);

setup_file = fullfile(bodyDir, [fname '_BAsetup.xml']);
tool.print(setup_file);
tool.run();

f = dir(fullfile(bodyDir, [fname '*.sto']));
for i = 1:numel(f)
    analysis_name = strrep(strrep(strrep(f(i).name, '_BodyKinematics_', ''), fname, ''), '.sto', '');
    data.body_results.(analysis_name) = load_sto_file(fullfile(f(i).folder, f(i).name));
end

disp('Body analysis complete.')
end